# Generated by Django 4.2.3 on 2023-07-25 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_product_price_product_state_alter_product_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
        migrations.RemoveField(
            model_name='product',
            name='name',
        ),
    ]
