# Generated by Django 5.0.2 on 2024-02-24 13:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manageport', '0002_rename_button_appliance'),
    ]

    operations = [
        migrations.AddField(
            model_name='appliance',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
